[mgr]
show_hidden = true
ratio = [2, 3, 4]

[plugin]
prepend_previewers = [
  { name = "*.tsv", run = "rich-preview" },
  { name = "*.ipynb", run = "nbpreview" },
]

# [opener]
# edit = [
#   { run = '$EDITOR "$@"', block = true, for = "unix", desc = "nvim" },
#   { run = "%EDITOR% %*", block = true, for = "windows" },
# ]
# view = [{ run = 'visidata $@', block = true, for = "unix", desc = "visidata" }]
# open = [{ run = 'xdg-open "$@"', desc = "Open" }]
# #
# [open]
# rules = [{ name = "*.csv", use = "view" }, { name = "*.json", use = ["edit", "view"] }]
